version: '3.8'

services:
  sentinel-gateway:
    build: .
    container_name: sentinel_core
    restart: unless-stopped
    ports:
      - "5000:5000"
    devices:
      # This explicitly passes the hardware through the isolation wall
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      # This maps the container's logs to your Pi's physical hard drive so they survive restarts
      - ~/iot_lab/logs:/root/iot_lab/logs
